# Generated by Django 5.2.7 on 2025-10-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_image', models.ImageField(upload_to='home/')),
                ('property_description', models.TextField()),
            ],
        ),
    ]
