# Generated by Django 5.2.7 on 2025-10-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_name',
        ),
        migrations.AddField(
            model_name='property',
            name='bhk_type',
            field=models.CharField(choices=[('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK')], default='2BHK', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='Nulol', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
