# Generated by Django 5.2.7 on 2025-10-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_property_property_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='projects/')),
                ('propert_bhk', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='property_brochures/'),
        ),
    ]
