# Generated by Django 5.2.7 on 2025-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_lead_email_alter_lead_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
