# Generated by Django 5.2.7 on 2025-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='partner_logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners_logo/'),
        ),
    ]
