# Generated by Django 5.2.7 on 2025-10-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_property_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
