# Generated by Django 5.2.7 on 2025-10-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_property_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='bhk_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
