# Generated by Django 5.2.7 on 2025-10-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_lead_bhk_type_lead_location_lead_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
