# Generated by Django 5.2.7 on 2025-10-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_contactmessage_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
