# Generated by Django 5.2.7 on 2025-10-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_contactmessage_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor_plane_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plan/'),
        ),
    ]
