# Generated by Django 5.2.7 on 2025-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_property_floor_plane_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sq_ft',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
