# Generated by Django 5.2.7 on 2025-10-31 11:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_property_sq_ft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bhk_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK')], default='2BHK', max_length=19),
        ),
        migrations.AlterField(
            model_name='property',
            name='sq_ft',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK')], default='2BHK', max_length=19),
        ),
    ]
