# Generated by Django 5.2.7 on 2025-10-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_property_bhk_type_alter_property_sq_ft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bhk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sq_ft',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
