# Generated by Django 5.2.7 on 2025-11-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_property_bhk_type_alter_property_sq_ft'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
