# Generated by Django 5.2.7 on 2025-11-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_property_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
