# Generated by Django 5.2.7 on 2025-11-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_property_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='selling_status',
            field=models.CharField(choices=[('Ready to Move', 'Ready to Move'), ('Under Construction', 'Under Construction'), ('Sold Out', 'Sold Out')], default='Ready to Move', max_length=30),
        ),
    ]
