# Generated by Django 5.2.7 on 2025-11-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_property_selling_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_properties', to='home.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
