# Generated by Django 5.2.7 on 2025-11-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_featuredlisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_title', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('featured_location', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_listings', to='home.property')),
            ],
        ),
        migrations.DeleteModel(
            name='FeaturedListing',
        ),
    ]
