# Generated by Django 5.2.7 on 2025-11-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_featurelisting_delete_featuredlisting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureListing',
        ),
    ]
