# Generated by Django 5.2.7 on 2025-11-02 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_delete_featurelisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('featured_location', models.CharField(blank=True, max_length=255, null=True)),
                ('featured_price', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
    ]
