# Generated by Django 5.2.7 on 2025-11-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_bannermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.property'),
        ),
    ]
