# Generated by Django 5.2.7 on 2025-11-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_propertyimage'),
        ('home', '0027_review_slogan'),
    ]

    operations = [
    ]
