# Generated by Django 5.2.7 on 2025-11-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_merge_0027_propertyimage_0027_review_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='slogan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
