# Generated by Django 5.2.7 on 2025-11-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_slogan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
