# Generated by Django 5.2.7 on 2026-01-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_aboutmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='image',
        ),
    ]
