# Generated by Django 5.2.7 on 2026-01-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_aboutmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('counts', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
