# Generated by Django 5.2.7 on 2026-01-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_propertycountmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='selling_status',
            field=models.CharField(choices=[('Ready to Move', 'Ready to Move'), ('Under Construction', 'Under Construction'), ('Sold Out', 'Sold Out'), ('Near Possession', 'Near Possession')], default='Ready to Move', max_length=30),
        ),
    ]
