# Generated by Django 5.2.7 on 2026-01-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_property_selling_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ph_number', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
