# Generated by Django 5.2.7 on 2026-01-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_slogan_is_banner_slogen'),
    ]

    operations = [
        migrations.AddField(
            model_name='slogan',
            name='is_banner_sub_slogen',
            field=models.BooleanField(default=False),
        ),
    ]
